dist: trusty
sudo: required
services:
  - docker
language: go
go:
- stable
- tip

env:
  - GOFLAGS=-mod=vendor TF_ACC_TERRAFORM_VERSION=0.15.0-alpha20210107

script:
- make test
- make vet
- make testacc

branches:
  only:
  - master
